package com.company.project.model;

import java.util.Date;

public class Compose {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.id
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.name
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.stack_id
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private String stackId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.is_stack_depend_on
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private Boolean isStackDependOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.create_time
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.update_time
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.status
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compose.content
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.id
     *
     * @return the value of compose.id
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.id
     *
     * @param id the value for compose.id
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.name
     *
     * @return the value of compose.name
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.name
     *
     * @param name the value for compose.name
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.stack_id
     *
     * @return the value of compose.stack_id
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public String getStackId() {
        return stackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.stack_id
     *
     * @param stackId the value for compose.stack_id
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setStackId(String stackId) {
        this.stackId = stackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.is_stack_depend_on
     *
     * @return the value of compose.is_stack_depend_on
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public Boolean getIsStackDependOn() {
        return isStackDependOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.is_stack_depend_on
     *
     * @param isStackDependOn the value for compose.is_stack_depend_on
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setIsStackDependOn(Boolean isStackDependOn) {
        this.isStackDependOn = isStackDependOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.create_time
     *
     * @return the value of compose.create_time
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.create_time
     *
     * @param createTime the value for compose.create_time
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.update_time
     *
     * @return the value of compose.update_time
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.update_time
     *
     * @param updateTime the value for compose.update_time
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.status
     *
     * @return the value of compose.status
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.status
     *
     * @param status the value for compose.status
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compose.content
     *
     * @return the value of compose.content
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compose.content
     *
     * @param content the value for compose.content
     *
     * @mbg.generated Sun Apr 21 20:18:48 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}