package com.company.project.model;

public class Setting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.key
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.value
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.unit
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.remark
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.key
     *
     * @return the value of setting.key
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.key
     *
     * @param key the value for setting.key
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.value
     *
     * @return the value of setting.value
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.value
     *
     * @param value the value for setting.value
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.unit
     *
     * @return the value of setting.unit
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.unit
     *
     * @param unit the value for setting.unit
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.remark
     *
     * @return the value of setting.remark
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.remark
     *
     * @param remark the value for setting.remark
     *
     * @mbg.generated Tue Apr 09 21:36:34 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}